version: '3.8'

services:
  postgres_db:
    image: postgres:13-alpine
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - ../storage/data:/var/lib/postgresql/data
      - ../config/postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - postgres_network
    command: ['postgres', '-c', 'config_file=/etc/postgresql/postgresql.conf']

networks:
  postgres_network:
    driver: bridge